const STREAM_EXTENSIONS = new Set([
  "ybn",
  "ydd",
  "ydr",
  "yft",
  "ymap",
  "ynv",
  "ytyp",
  "ytd",
]);

const DATA_EXTENSIONS = new Set([
  "dat",
  "meta",
  "rel",
  "ymt",
  "xml",
]);

const EXCLUDED_EXTENSIONS = new Set([
  "gxt2",
]);

const META_DATA_FILE_TYPES: Array<{ pattern: RegExp; type: string }> = [
  { pattern: /(^|\/)handling\.meta$/i, type: "HANDLING_FILE" },
  { pattern: /(^|\/)vehicles\.meta$/i, type: "VEHICLE_METADATA_FILE" },
  { pattern: /(^|\/)carcols\.meta$/i, type: "CARCOLS_FILE" },
  { pattern: /(^|\/)carvariations\.meta$/i, type: "VEHICLE_VARIATION_FILE" },
  { pattern: /(^|\/)vehiclelayouts\.meta$/i, type: "VEHICLE_LAYOUTS_FILE" },
  { pattern: /(^|\/)contentunlocks\.meta$/i, type: "CONTENT_UNLOCKING_META" },
  { pattern: /(^|\/)dlctext\.meta$/i, type: "DLC_TEXT_FILE" },
  { pattern: /(^|\/)weapon(?:animations|archetypes|components|pedpersonality|s)?\.meta$/i, type: "WEAPONINFO_FILE" },
  { pattern: /(^|\/)weapon(?:animations|archetypes|components|pedpersonality|s)?[^/]*\.meta$/i, type: "WEAPONINFO_FILE" },
  { pattern: /(^|\/)pedpersonality\.meta$/i, type: "PED_PERSONALITY_FILE" },
  { pattern: /(^|\/)peds\.meta$/i, type: "PED_METADATA_FILE" },
  { pattern: /(^|\/)shop_vehicle\.meta$/i, type: "VEHICLE_SHOP_DLC_FILE" },
];

export interface FiveMResourceFile {
  sourcePath: string;
  resourcePath: string;
  data: Uint8Array;
}

export interface FiveMResourceBuildResult {
  rootName: string;
  files: FiveMResourceFile[];
  manifest: string;
}

export function buildFiveMResourceFiles(
  sourceFiles: Map<string, Uint8Array>,
  sourceFileName: string,
): FiveMResourceBuildResult {
  const rootName = sanitizeResourceName(sourceFileName.replace(/\.rpf$/i, ""));
  const files: FiveMResourceFile[] = [];
  const usedResourcePaths = new Set<string>();

  for (const [sourcePath, data] of sourceFiles) {
    const normalizedPath = normalizeArchivePath(sourcePath);
    if (!normalizedPath || shouldExcludeFromResource(normalizedPath)) continue;

    const resourcePath = getUniqueResourcePath(
      getFiveMResourcePath(normalizedPath),
      usedResourcePaths,
    );

    files.push({
      sourcePath: normalizedPath,
      resourcePath,
      data,
    });
  }

  files.sort((a, b) => a.resourcePath.localeCompare(b.resourcePath));

  return {
    rootName,
    files,
    manifest: createFxManifest(files),
  };
}

function sanitizeResourceName(name: string): string {
  const normalized = name
    .trim()
    .replace(/[^a-zA-Z0-9_-]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .toLowerCase();

  return normalized || "fivem_resource";
}

function normalizeArchivePath(path: string): string {
  return path
    .replace(/\\/g, "/")
    .replace(/^\/+/, "")
    .replace(/(?:^|\/)\.\.(?=\/|$)/g, "")
    .split("/")
    .filter(Boolean)
    .join("/");
}

function shouldExcludeFromResource(path: string): boolean {
  return EXCLUDED_EXTENSIONS.has(getExtension(path));
}

function getFiveMResourcePath(path: string): string {
  const first = path.toLowerCase().split("/")[0];
  const ext = getExtension(path);

  if (STREAM_EXTENSIONS.has(ext)) return `stream/${getBaseName(path)}`;
  if (first === "data") return path;
  if (DATA_EXTENSIONS.has(ext)) return `data/${path}`;
  if (first === "stream") return `stream/${getBaseName(path)}`;
  return `stream/${getBaseName(path)}`;
}

function getUniqueResourcePath(path: string, usedPaths: Set<string>): string {
  if (!usedPaths.has(path)) {
    usedPaths.add(path);
    return path;
  }

  const slashIndex = path.lastIndexOf("/");
  const folder = slashIndex >= 0 ? path.slice(0, slashIndex + 1) : "";
  const fileName = slashIndex >= 0 ? path.slice(slashIndex + 1) : path;
  const dotIndex = fileName.lastIndexOf(".");
  const name = dotIndex >= 0 ? fileName.slice(0, dotIndex) : fileName;
  const extension = dotIndex >= 0 ? fileName.slice(dotIndex) : "";

  let index = 2;
  let candidate = `${folder}${name}_${index}${extension}`;
  while (usedPaths.has(candidate)) {
    index++;
    candidate = `${folder}${name}_${index}${extension}`;
  }

  usedPaths.add(candidate);
  return candidate;
}

function getExtension(path: string): string {
  return path.split(".").pop()?.toLowerCase() ?? "";
}

function getBaseName(path: string): string {
  return path.split("/").pop() ?? path;
}

function createFxManifest(files: FiveMResourceFile[]): string {
  const dataFiles = files.filter((file) => file.resourcePath.startsWith("data/"));
  const ytypFiles = files.filter((file) => file.resourcePath.toLowerCase().endsWith(".ytyp"));
  const manifestLines = [
    "fx_version 'cerulean'",
    "game 'gta5'",
    "",
    "author 'Generated by RAGE File Viewer'",
    "description 'FiveM resource exported from an RPF archive'",
  ];

  if (dataFiles.length > 0) {
    manifestLines.push("", "files {");
    for (const file of dataFiles) {
      manifestLines.push(`  '${escapeLuaString(file.resourcePath)}',`);
    }
    manifestLines.push("}");
  }

  for (const file of ytypFiles) {
    manifestLines.push(`data_file 'DLC_ITYP_REQUEST' '${escapeLuaString(file.resourcePath)}'`);
  }

  const dataFileLines = createDataFileLines(dataFiles);
  if (dataFileLines.length > 0) {
    manifestLines.push(...dataFileLines);
  }

  manifestLines.push("");
  return manifestLines.join("\n");
}

function createDataFileLines(files: FiveMResourceFile[]): string[] {
  const lines: string[] = [];
  const seen = new Set<string>();

  for (const file of files) {
    const type = getDataFileType(file.resourcePath);
    if (!type) continue;

    const line = `data_file '${type}' '${escapeLuaString(file.resourcePath)}'`;
    if (!seen.has(line)) {
      seen.add(line);
      lines.push(line);
    }
  }

  return lines;
}

function getDataFileType(path: string): string | null {
  for (const { pattern, type } of META_DATA_FILE_TYPES) {
    if (pattern.test(path)) return type;
  }
  return null;
}

function escapeLuaString(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/'/g, "\\'");
}
